# Tensor
    - Specialized data structure that is very similar to arrays and matrices
    - In Pytorch, tensor is use to encode the inputs and outputs of the model, as well as the model's parameters
    - Tensors are similiar to numpy.array except it can be run on GPUs or other specialized hardware to accelerate computing

In [195]:
import torch
import numpy as np

# Tensor Initialization
    - Tensor can be initiated in various way   

## Directly from data 
    - data type is automatically inferred

In [196]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

## From a Numpy array
    - Created from Numpy array and vice versa (Bridge with Numpy)

In [197]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

## From another tensor
    - The new tensor retain the properties (shape, datatype) of the argument tensor, unless explicitly overriden 

In [198]:
# Retains the properties of x_data
x_ones = torch.ones_like(x_data)
print(f"One tensor: \n{x_ones} \n")
# Overrides the datatypes of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n{x_rand}\n")

One tensor: 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
tensor([[0.6929, 0.1703],
        [0.1384, 0.4759]])



## With random or constant value
    - 'shape' is a tuple of dimensions  
    - You can declare the data types of the tensor

In [199]:
shape = (2, 3, )
ones_tensor = torch.ones(shape, dtype=torch.int16)
zeros_tensor = torch.zeros(shape, dtype=torch.float64)
# For random, select seed because it is pseudorandom
torch.manual_seed(1729)
rand_tensor = torch.rand(shape)

print(f"Random Tensor: \n {rand_tensor}\n")
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


# Tensor Attributes
    - Tensor attributes describe their shape, datatype, and the device on which they are stored

In [200]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatpype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatpype of tensor: torch.float32
Device tensor is stored on cpu


# Tensor Operation
    - Over 100 tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more
    - Each of them can be run on the GPU (at typically higher speeds than on a CPU)
    - If using Colab, allocate a GPU by going to Edit/Notebook settings

In [201]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


## Standard numpy-like indexing and slicing

In [202]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Joining tensors
    - You can use `torch.cat` to cancaternate a sequence of tensors along a given dimension
    - `torch.stack` is another tensor joining op that is subtly different from `torch.cat`

In [203]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## Multiplying tensors

In [204]:
# This compute the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)}\n")
# Alternative syntax
print(f"tensor * tensor \n {tensor*tensor}\n")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



In [205]:
# This compute the matrix multiplication between two tensors
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)}\n")
#Alternative syntax
print(f"tensor @ tensor.t \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor @ tensor.t 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


## In-place operations
    - Operations that have a `_` suffix are in place
    - For example: 'x.copy_()`, `x.t_()` will change x
    - In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [206]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with NumPy
    - Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

## Tensor to NumPy array
    - A change in tensor reflects in the NumPy array

In [207]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
# Show changes
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor
    - Changes in the NumPy array reflects in the tensor

In [208]:
n = np.ones(5)
t = torch.from_numpy(n)
# Show changes
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
